[package]
name = "inline-kube"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.55"
rustkube = { path = "../rustkube" }
serde_yaml = "0.8.23"
